"""Add provider to dose

Revision ID: 50c823da3252
Revises: c7eee4522a8e
Create Date: 2026-03-22 21:02:50.718014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50c823da3252'
down_revision = 'c7eee4522a8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dose', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dose', schema=None) as batch_op:
        batch_op.drop_column('provider')

    # ### end Alembic commands ###
