"""Add total_doses to vaccination

Revision ID: c7eee4522a8e
Revises: 719b0471f5a9
Create Date: 2026-03-09 19:25:32.391662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7eee4522a8e'
down_revision = '719b0471f5a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.alter_column('relationship',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'child'"))

    with op.batch_alter_table("vaccination") as batch_op:
        batch_op.add_column(
            sa.Column(
                "total_doses",
                sa.Integer(),
                nullable=False,
                server_default="1"
            )
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vaccination', schema=None) as batch_op:
        batch_op.drop_column('total_doses')

    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.alter_column('relationship',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'child'"))

    # ### end Alembic commands ###
